### ISSUE TITLE
Clarity in README.md question/suggestion.

### ISSUE THREAD

**Issue by cascala** [mfirry/web-frameworks-templates#20]
What are the numbers prior to the framework name in the README file?
E.g. 335 and 4.

(335)   akka-http
(4)     analogweb

Thanks!!!

**Comment by mfirry** [comment]
Hi,
they should be the number of github stars that particular repo has.

I was suppose to update that frequently but... I always forget. I might remove it at some point.

**Comment by cascala** [comment]
Thanks @mfirry 

You could write that in the readme... It's not clear at all :)

Thanks again!!! Nice project.
